// ***Manejo de errores***

try{
    console.log("En el try se agrega el código a evaluar");
} catch (error) {
    console.log("Catch, captura cualquier error surgido o lanzado en el try");
} finally{
    console.log("Se ejecutará al final de un try-catch");
}